baseURL = "https://edesibe.github.io/resume"
languageCode = "en-us"
theme = "almeida-cv"
title = "My Resume"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#c2e4b9"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 1
