baseURL = "https://edesibe.github.io/resume"
languageCode = "en-us"
theme = "almeida-cv"
title = "My Resume"
publishDir = "docs"


#[params]
#colorDark = "#666"
#colorLight = "#fff"
#colorPageBackground = "#ddd"
#colorPrimary = "#c2e4b9"
#colorPrimaryText = "#fff"
#colorRightColumnBackground = "#f5f5f5"
#colorSecondary = "#aaa"
#pages = 2

[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#ddd"
colorPrimary = "#c2e4b9"
colorSecondary = "#aaa"
colorIconPrimary = "#fff"
colorIconBackground = "#c2e4b9"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#c2e4b9"
pages = 2
# Set this param to 'true' to swap the bar positions
swapColumns = false
